spring:
  profiles:
    group:
      default: dev
      dev: common,log-console,db,db-h2-file,log4jdbc,prometheus
      local: common,log-file,db,db-h2-file,prometheus
      prod: common,log-file,db,db-mysql,prometheus
  application:
    name: peacetrue-application-webmvc
