# Spring Boot Admin 配置

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    boot:
        admin:
            client:
                instance:
                    service-base-url: ${spring.application.url}/api
                url: ${spring.application.url}/monitor
