spring:
  profiles:
    group:
      default: dev
      dev: common,log-console,db,db-h2-file,date-format,prometheus
      local: common,log-file,db,db-h2-file,date-format,prometheus
      prod: common,log-file,db,db-mysql,date-format,prometheus
  application:
    name: peacetrue-application-webmvc
