#spring.config.activate.on-profile: db-h2-file

spring:
  r2dbc:
    url: r2dbc:h2:file:///./${db.schema};DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  flyway:
    url: jdbc:h2:file:./${db.schema};DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE

